### ISSUE TITLE
ESP32 board support

### ISSUE THREAD

**Issue by gnoeee** [spaceneedle/Chromeduino#16]
I would like to work on ESP boards.

But when i checked the board list, currently its not showing up.

Is it possible to add ESP 32 boards.

I am using ESP32 devkit v1

**Comment by mrfrase3** [comment]
Hey @jinoytommanjaly,

I'd love to support it, but ESP boards have a completely different upload protocol.

This means chromeduino would need to be recoded to support this, which I've been doing on-and-off for the past year, you can see the progress in #12
