### ISSUE TITLE
Ad 

### ISSUE THREAD

**Issue by Nikolast78** [spaceneedle/Chromeduino#18]

**Comment by Nikolast78** [comment]
Hello, i would like to add libraries (like Adafruit) in Chromeduino 2, but i don't know how to do... any idea ?

**Comment by mrfrase3** [comment]
Hey, sorry for the late reply.

Please select the compile server legacy.duino.app, it currently has every library installed. Just import whatever you want in the code.

**Comment by Nikolast78** [comment]
Thank you. 
But where can I find this legacy.duino.app ?
In my start page, i only have 3 choices, and none of them is the good one.
