### ISSUE TITLE
Where is the server for Chromeduino2 ... it looks like my school is blocking the server as students can't connect to it when opening Chromeduinow

### ISSUE THREAD

**Issue by ochs-tf-t** [spaceneedle/Chromeduino#21]

**Comment by mrfrase3** [comment]
You'll need to speak to your IT department to fix this, or run your own server on the network.

The domain they need to allow is legacy.duino.app

You can also look at version 3 at https://duino.app

**Comment by ochs-tf-t** [comment]
I need to know the actual server & address so my tech department can put
the server on the "allowed" list ... I did not see any way of identifying
the url for the server within the app

**Comment by ochs-tf-t** [comment]
does duino.app work for chromebooks?

**Comment by mrfrase3** [comment]
You're probably only looking at this via email, I edited my last message to include the address you need to allow, it's legacy.duino.app

And yes, version 3 works on Chromebooks as well as other operating systems, although features/board support is still being rolled out.
