### ISSUE TITLE
Boards and Libraries

### ISSUE THREAD

**Issue by mrfrase3** [spaceneedle/Chromeduino#3]
The ability to add new boards and libraries would be cool. Like the ESP8266 board, or the WS2812 libraries.

### Client Side Problems
Support for boards will require writing new programming protocols to the client app.

###  Server Side Problem
The main problem is the remote compile server, there are three ways to do it; 
 - people run servers with pre-defined boards installed (not dynamic), 
 - a server downloads and caches anything when requested (waste storage), or 
 - a server downloads them as requested and delete them after every time they compile (waste bandwidth)?

Maybe have board libraries supported and maintained in separate repos, and then people can load in the programming protocols as needed. Our own board library?

## Libraries

Libraries suffer a similar dilemma to boards on the server side;
 - does a client upload or link libraries needed every time they compile?
 - do servers have a pre-defined list of installed libraries?
 - does the server cache libraries?

Side note: Google is planning on bringing Linux programs to ChromeOS, so putting a lot of effort into one solution may prove pointless if the Arduino IDE can be installed on Chromebooks in the near future. Conversely, Arduino may not allow this seeming they get revenue from Chromebooks...

**Comment by ethansmi** [comment]
The Linux program is Beta and does not work on all Chromebooks. It would make sense to be able to use libraries. Also, if I want to be able to work on projects on the fly, then it is really inconvenient to have to work without libraries.

**Comment by mrfrase3** [comment]
Yeh, I can agree. Here we are, a year later and Linux apps is still a dumpster fire. Google also shot themselves in the foot by letting vendors sell Chromebooks with 16-32GB of soldered-on storage, which only just enough to fit two operating systems on.

The AWS lambda seems like a decent option, allow people to download whatever resources are needed, compile, then delete the instance, maybe caching the libraries/boards in an S3...

I'm trying to find time to try something out with virtual usb interfaces, if it works out, then adding this support will become a lot easier.
